"""POST /agent/ask — the natural-language agent entry point. GET endpoints expose the
conversation audit trail, scoped to the caller's org (see store.py / orchestrator.py for
the mechanics; safety.py for why raw SQL is never generated by the LLM).
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from psycopg import Connection

from service.app.config import Settings, get_settings
from service.app.deps import CurrentPrincipal, get_current_principal, get_db
from service.app.schemas.agent import (
    AskRequest,
    AskResponse,
    ConversationDetail,
    ConversationMessage,
    ConversationSummary,
    MapPayload,
    ToolTraceEntry,
)
from service.app.services import tenancy_service
from service.app.services.agent import store
from service.app.services.agent.llm_provider import get_llm_provider
from service.app.services.agent.orchestrator import run_agent_turn

router = APIRouter(prefix="/agent", tags=["agent"])


def _require_feed_access(conn: Connection, principal: CurrentPrincipal, feed_id: str) -> None:
    visible = tenancy_service.resolve_visible_feed_ids(conn, org_id=principal.org_id)
    if feed_id not in visible:
        raise HTTPException(status.HTTP_403_FORBIDDEN, f"No access to feed '{feed_id}'")


@router.post("/ask", response_model=AskResponse)
def ask(
    body: AskRequest,
    principal: CurrentPrincipal = Depends(get_current_principal),
    conn: Connection = Depends(get_db),
    settings: Settings = Depends(get_settings),
) -> AskResponse:
    _require_feed_access(conn, principal, body.feed_id)

    if body.conversation_id is not None:
        existing = store.get_conversation(
            conn, org_id=principal.org_id, conversation_id=body.conversation_id
        )
        if existing is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Conversation not found")
        if existing["feed_id"] != body.feed_id:
            raise HTTPException(
                status.HTTP_400_BAD_REQUEST, "feed_id does not match this conversation"
            )
        conversation_id = body.conversation_id
        history = [
            {"role": row["role"], "content": row["content"]}
            for row in store.list_messages(conn, conversation_id=conversation_id)
        ]
    else:
        conversation_id = store.create_conversation(
            conn, org_id=principal.org_id, user_id=principal.user_id, feed_id=body.feed_id
        )
        history = []

    llm = get_llm_provider(settings)
    turn = run_agent_turn(
        conn,
        org_id=principal.org_id,
        feed_id=body.feed_id,
        question=body.question,
        history=history,
        llm=llm,
        settings=settings,
    )

    store.append_message(conn, conversation_id=conversation_id, role="user", content=body.question)
    store.append_message(
        conn,
        conversation_id=conversation_id,
        role="assistant",
        content=turn["answer"],
        tool_calls=turn["tool_trace"],
    )
    conn.commit()

    return AskResponse(
        conversation_id=conversation_id,
        answer=turn["answer"],
        map_payload=MapPayload(points=turn["map_points"]),
        tool_trace=[ToolTraceEntry(**t) for t in turn["tool_trace"]],
    )


@router.get("/conversations", response_model=list[ConversationSummary])
def list_conversations(
    principal: CurrentPrincipal = Depends(get_current_principal),
    conn: Connection = Depends(get_db),
) -> list[ConversationSummary]:
    return [ConversationSummary(**row) for row in store.list_conversations(conn, org_id=principal.org_id)]


@router.get("/conversations/{conversation_id}", response_model=ConversationDetail)
def get_conversation_detail(
    conversation_id: uuid.UUID,
    principal: CurrentPrincipal = Depends(get_current_principal),
    conn: Connection = Depends(get_db),
) -> ConversationDetail:
    conversation = store.get_conversation(conn, org_id=principal.org_id, conversation_id=conversation_id)
    if conversation is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Conversation not found")
    messages = store.list_messages(conn, conversation_id=conversation_id)
    return ConversationDetail(
        conversation_id=conversation["conversation_id"],
        feed_id=conversation["feed_id"],
        created_at=conversation["created_at"],
        messages=[ConversationMessage(role=m["role"], content=m["content"]) for m in messages],
    )
